version: "3.8"

services:
  # MySQL测试数据库
  mysql-test:
    image: mysql:8.0
    container_name: farmgear-mysql-test
    environment:
      MYSQL_ROOT_PASSWORD: test123456
      MYSQL_DATABASE: FarmGearTestDb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: test123456
    ports:
      - "3307:3306"
    volumes:
      - mysql_test_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Redis测试缓存
  redis-test:
    image: redis:7-alpine
    container_name: farmgear-redis-test
    ports:
      - "6380:6379"
    volumes:
      - redis_test_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 20s
      retries: 10

volumes:
  mysql_test_data:
  redis_test_data:
